//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 02:02:00 PM PDT 
//

//package com.ciphercloud.xmlns.upgrade;
package com.ciphercloud.upgrade.definitions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ResourceKey complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceKey">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="resourceKeySpec" type="{http://xmlns.ciphercloud.com/upgrade}ResourceKeySpec"/>
 *         &lt;element name="history" type="{http://xmlns.ciphercloud.com/upgrade}History" minOccurs="0"/>
 *         &lt;element name="delegateClass" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="reviewed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/*@XmlType(name = "ResourceKey", propOrder = {
    "owner",
    "resourceKeySpec",
    "history",
    "delegateClass"
})*/
@XmlRootElement(name="ResourceKey")
@XmlAccessorType(XmlAccessType.FIELD)
public class ResourceKey {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String owner;
    @XmlElement
    protected ResourceKeySpec resourceKeySpec;
   	// protected History history;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String delegateClass;
    @XmlAttribute(name = "reviewed")
    protected Boolean reviewed;
    
    @XmlElement(required = true)
    protected String action;
    
    public ResourceKeySpec getResourceKeySpec() {
		return resourceKeySpec;
	}

	public void setResourceKeySpec(ResourceKeySpec resourceKeySpec) {
		this.resourceKeySpec = resourceKeySpec;
	}
	
	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}
    
    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the resourceKeySpec property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceKeySpec }
     *     
     */
   /* public ResourceKeySpec getResourceKeySpec() {
        return resourceKeySpec;
    }
    */

    /**
     * Sets the value of the resourceKeySpec property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceKeySpec }
     *     
     */
   /* public void setResourceKeySpec(ResourceKeySpec value) {
        this.resourceKeySpec = value;
    }
    */

    /**
     * Gets the value of the history property.
     * 
     * @return
     *     possible object is
     *     {@link History }
     *     
     */
/*    public History getHistory() {
        return history;
    }
*/
    /**
     * Sets the value of the history property.
     * 
     * @param value
     *     allowed object is
     *     {@link History }
     *     
     */
   /* public void setHistory(History value) {
        this.history = value;
    }
*/
    /**
     * Gets the value of the delegateClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegateClass() {
        return delegateClass;
    }

    /**
     * Sets the value of the delegateClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegateClass(String value) {
        this.delegateClass = value;
    }

    /**
     * Gets the value of the reviewed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReviewed() {
        return reviewed;
    }

    /**
     * Sets the value of the reviewed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReviewed(Boolean value) {
        this.reviewed = value;
    }

}
