//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 02:02:00 PM PDT 
//


//package com.ciphercloud.xmlns.upgrade;
package com.ciphercloud.upgrade.definitions;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SystemDefs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SystemDefs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="preUpgrade" type="{http://xmlns.ciphercloud.com/upgrade}PreUpgrade" minOccurs="0"/>
 *         &lt;element name="systemDef" type="{http://xmlns.ciphercloud.com/upgrade}SystemDef" maxOccurs="unbounded"/>
 *         &lt;element name="postUpgradeBeforeImport" type="{http://xmlns.ciphercloud.com/upgrade}PostUpgradeBeforeImport" minOccurs="0"/>
 *         &lt;element name="postUpgradeAfterImport" type="{http://xmlns.ciphercloud.com/upgrade}PostUpgradeAfterImport" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/*@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SystemDefs", propOrder = {
   // "preUpgrade",
    "systemDef",
   // "postUpgradeBeforeImport",
   // "postUpgradeAfterImport"
})*/

@XmlRootElement(name="SystemChangeDefs")
@XmlAccessorType(XmlAccessType.FIELD)

public class SystemChangeDefs {

//    protected PreUpgrade preUpgrade;
    @XmlElement(required = true)
	public List<SystemChangeDef> systemChangeDef;
//    protected PostUpgradeBeforeImport postUpgradeBeforeImport;
//    protected PostUpgradeAfterImport postUpgradeAfterImport;

	public void setSystemDef(List<SystemChangeDef> systemDef) {
		this.systemChangeDef = systemDef;
	}
	 public List<SystemChangeDef> getSystemDef() {
	        if (systemChangeDef == null) {
	            systemChangeDef = new ArrayList<SystemChangeDef>();
	        }
	        return this.systemChangeDef;
	    }
    
}
