//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 02:02:00 PM PDT 
//

//package com.ciphercloud.xmlns.upgrade;
package com.ciphercloud.xmlns.upgrade;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for History complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="History">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="historyResourceKeySpec" type="{http://xmlns.ciphercloud.com/upgrade}HistoryResourceKeySpec"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "History", propOrder = {
    "historyResourceKeySpec"
})
public class History {

    @XmlElement(required = true)
    protected HistoryResourceKeySpec historyResourceKeySpec;

    /**
     * Gets the value of the historyResourceKeySpec property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryResourceKeySpec }
     *     
     */
    public HistoryResourceKeySpec getHistoryResourceKeySpec() {
        return historyResourceKeySpec;
    }

    /**
     * Sets the value of the historyResourceKeySpec property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryResourceKeySpec }
     *     
     */
    public void setHistoryResourceKeySpec(HistoryResourceKeySpec value) {
        this.historyResourceKeySpec = value;
    }

}
