//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 02:02:00 PM PDT 
//


//package com.ciphercloud.xmlns.upgrade;
package com.ciphercloud.xmlns.upgrade;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.ciphercloud.upgrade.definitions.ResourceKey;
import com.ciphercloud.upgrade.definitions.ResourceKeySpec;
import com.ciphercloud.upgrade.definitions.SystemChangeDef;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ciphercloud.xmlns.upgrade package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SystemDefs_QNAME = new QName("http://xmlns.ciphercloud.com/upgrade", "systemDefs");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ciphercloud.xmlns.upgrade
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SystemDefs }
     * 
     */
    public SystemDefs createSystemDefs() {
        return new SystemDefs();
    }

    /**
     * Create an instance of {@link HistoryResourceKeySpec }
     * 
     */
    public HistoryResourceKeySpec createHistoryResourceKeySpec() {
        return new HistoryResourceKeySpec();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link PostUpgradeAfterImport }
     * 
     */
    public PostUpgradeAfterImport createPostUpgradeAfterImport() {
        return new PostUpgradeAfterImport();
    }

    /**
     * Create an instance of {@link PostUpgradeProcess }
     * 
     */
    public PostUpgradeProcess createPostUpgradeProcess() {
        return new PostUpgradeProcess();
    }

    /**
     * Create an instance of {@link PreUpgradeProcess }
     * 
     */
    public PreUpgradeProcess createPreUpgradeProcess() {
        return new PreUpgradeProcess();
    }

    /**
     * Create an instance of {@link SystemChangeDef }
     * 
     */
    public SystemChangeDef createSystemDef() {
        return new SystemChangeDef();
    }

    /**
     * Create an instance of {@link PostUpgradeBeforeImport }
     * 
     */
    public PostUpgradeBeforeImport createPostUpgradeBeforeImport() {
        return new PostUpgradeBeforeImport();
    }

    /**
     * Create an instance of {@link ResourceKeySpec }
     * 
     */
    public ResourceKeySpec createResourceKeySpec() {
        return new ResourceKeySpec();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link PreUpgrade }
     * 
     */
    public PreUpgrade createPreUpgrade() {
        return new PreUpgrade();
    }

    /**
     * Create an instance of {@link ResourceKey }
     * 
     */
    public ResourceKey createResourceKey() {
        return new ResourceKey();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemDefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.ciphercloud.com/upgrade", name = "systemDefs")
    public JAXBElement<SystemDefs> createSystemDefs(SystemDefs value) {
        return new JAXBElement<SystemDefs>(_SystemDefs_QNAME, SystemDefs.class, null, value);
    }

}
