//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 02:02:00 PM PDT 
//


//package com.ciphercloud.xmlns.upgrade;
package com.ciphercloud.xmlns.upgrade;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PostUpgradeBeforeImport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PostUpgradeBeforeImport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="postUpgradeProcess" type="{http://xmlns.ciphercloud.com/upgrade}PostUpgradeProcess" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostUpgradeBeforeImport", propOrder = {
    "postUpgradeProcess"
})
public class PostUpgradeBeforeImport {

    protected List<PostUpgradeProcess> postUpgradeProcess;

    /**
     * Gets the value of the postUpgradeProcess property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the postUpgradeProcess property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPostUpgradeProcess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PostUpgradeProcess }
     * 
     * 
     */
    public List<PostUpgradeProcess> getPostUpgradeProcess() {
        if (postUpgradeProcess == null) {
            postUpgradeProcess = new ArrayList<PostUpgradeProcess>();
        }
        return this.postUpgradeProcess;
    }

}
