//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 02:02:00 PM PDT 
//


//package com.ciphercloud.xmlns.upgrade;
package com.ciphercloud.xmlns.upgrade;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.ciphercloud.upgrade.definitions.SystemChangeDef;


/**
 * <p>Java class for SystemDefs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SystemDefs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="preUpgrade" type="{http://xmlns.ciphercloud.com/upgrade}PreUpgrade" minOccurs="0"/>
 *         &lt;element name="systemDef" type="{http://xmlns.ciphercloud.com/upgrade}SystemDef" maxOccurs="unbounded"/>
 *         &lt;element name="postUpgradeBeforeImport" type="{http://xmlns.ciphercloud.com/upgrade}PostUpgradeBeforeImport" minOccurs="0"/>
 *         &lt;element name="postUpgradeAfterImport" type="{http://xmlns.ciphercloud.com/upgrade}PostUpgradeAfterImport" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SystemDefs", propOrder = {
    "preUpgrade",
    "systemDef",
    "postUpgradeBeforeImport",
    "postUpgradeAfterImport"
})
public class SystemDefs {

    protected PreUpgrade preUpgrade;
    @XmlElement(required = true)
    protected List<SystemChangeDef> systemDef;
    protected PostUpgradeBeforeImport postUpgradeBeforeImport;
    protected PostUpgradeAfterImport postUpgradeAfterImport;

    /**
     * Gets the value of the preUpgrade property.
     * 
     * @return
     *     possible object is
     *     {@link PreUpgrade }
     *     
     */
    public PreUpgrade getPreUpgrade() {
        return preUpgrade;
    }

    /**
     * Sets the value of the preUpgrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreUpgrade }
     *     
     */
    public void setPreUpgrade(PreUpgrade value) {
        this.preUpgrade = value;
    }

    /**
     * Gets the value of the systemDef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemDef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystemDef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SystemChangeDef }
     * 
     * 
     */
    public List<SystemChangeDef> getSystemDef() {
        if (systemDef == null) {
            systemDef = new ArrayList<SystemChangeDef>();
        }
        return this.systemDef;
    }

    /**
     * Gets the value of the postUpgradeBeforeImport property.
     * 
     * @return
     *     possible object is
     *     {@link PostUpgradeBeforeImport }
     *     
     */
    public PostUpgradeBeforeImport getPostUpgradeBeforeImport() {
        return postUpgradeBeforeImport;
    }

    /**
     * Sets the value of the postUpgradeBeforeImport property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostUpgradeBeforeImport }
     *     
     */
    public void setPostUpgradeBeforeImport(PostUpgradeBeforeImport value) {
        this.postUpgradeBeforeImport = value;
    }

    /**
     * Gets the value of the postUpgradeAfterImport property.
     * 
     * @return
     *     possible object is
     *     {@link PostUpgradeAfterImport }
     *     
     */
    public PostUpgradeAfterImport getPostUpgradeAfterImport() {
        return postUpgradeAfterImport;
    }

    /**
     * Sets the value of the postUpgradeAfterImport property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostUpgradeAfterImport }
     *     
     */
    public void setPostUpgradeAfterImport(PostUpgradeAfterImport value) {
        this.postUpgradeAfterImport = value;
    }

}
