//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 02:02:00 PM PDT 
//


package com.ciphercloud.xmlns.upgrade;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.ciphercloud.upgrade.definitions.ResourceKeySpec;


/**
 * <p>Java class for Version complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Version">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="buildNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resourceKeySpec" type="{http://xmlns.ciphercloud.com/upgrade}ResourceKeySpec" minOccurs="0"/>
 *         &lt;element name="resourceContainer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="delegateClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resourceKeyValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Version", propOrder = {
    "buildNumber",
    "resourceKeySpec",
    "resourceContainer",
    "delegateClass",
    "resourceKeyValue"
})
public class Version {

    protected String buildNumber;
    protected ResourceKeySpec resourceKeySpec;
    @XmlElement(required = true)
    protected String resourceContainer;
    protected String delegateClass;
    protected String resourceKeyValue;
    @XmlAttribute(name = "value")
    protected String value;

    /**
     * Gets the value of the buildNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildNumber() {
        return buildNumber;
    }

    /**
     * Sets the value of the buildNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildNumber(String value) {
        this.buildNumber = value;
    }

    /**
     * Gets the value of the resourceKeySpec property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceKeySpec }
     *     
     */
    public ResourceKeySpec getResourceKeySpec() {
        return resourceKeySpec;
    }

    /**
     * Sets the value of the resourceKeySpec property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceKeySpec }
     *     
     */
    public void setResourceKeySpec(ResourceKeySpec value) {
        this.resourceKeySpec = value;
    }

    /**
     * Gets the value of the resourceContainer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceContainer() {
        return resourceContainer;
    }

    /**
     * Sets the value of the resourceContainer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceContainer(String value) {
        this.resourceContainer = value;
    }

    /**
     * Gets the value of the delegateClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegateClass() {
        return delegateClass;
    }

    /**
     * Sets the value of the delegateClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegateClass(String value) {
        this.delegateClass = value;
    }

    /**
     * Gets the value of the resourceKeyValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceKeyValue() {
        return resourceKeyValue;
    }

    /**
     * Sets the value of the resourceKeyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceKeyValue(String value) {
        this.resourceKeyValue = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
